bet_amount = ""
current_balance = ""
market_id = ""
merkle_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
merkle_path_indices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
merkle_root = ""
new_commitment = ""
nonce = ""
nullifier = ""
nullifier_of_bet = ""
secret = ""
