// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test, console2} from "forge-std/Test.sol";

// snarkjs-generated Groth16 verifiers (one per circuit)
import {Groth16Verifier as BetAuthVerifier}         from "@groth16/generated/BetAuthVerifier.sol";
import {Groth16Verifier as SettlementVerifier}       from "@groth16/generated/SettlementCreditVerifier.sol";
import {Groth16Verifier as WithdrawalVerifier}       from "@groth16/generated/WithdrawalVerifier.sol";
import {Groth16Verifier as BetCancelVerifier}        from "@groth16/generated/BetCancelVerifier.sol";
import {Groth16Verifier as CancelCreditVerifier}     from "@groth16/generated/CancelCreditVerifier.sol";

// IVerifier adapters (bridge snarkjs verifier ↔ Vault's IVerifier interface)
import {BetAuthGroth16Adapter}         from "@groth16/adapters/BetAuthGroth16Adapter.sol";
import {SettlementCreditGroth16Adapter} from "@groth16/adapters/SettlementCreditGroth16Adapter.sol";
import {WithdrawalGroth16Adapter}       from "@groth16/adapters/WithdrawalGroth16Adapter.sol";
import {BetCancelGroth16Adapter}        from "@groth16/adapters/BetCancelGroth16Adapter.sol";
import {CancelCreditGroth16Adapter}     from "@groth16/adapters/CancelCreditGroth16Adapter.sol";

/// @notice On-chain Groth16 verification gas benchmark for all 5 Polyshield circuits.
/// Proofs are generated by: cd packages/groth16 && npm run generate:test-proofs
/// Run: cd packages/contracts && forge test --match-contract ZkGasBenchGroth16 --gas-report -vv
contract ZkGasBenchGroth16Test is Test {
    string constant BENCH = "../groth16/bench_out/";

    // ── Raw verifiers (from snarkjs export solidityverifier) ──────────────────
    BetAuthVerifier         verifier_bet_auth;
    SettlementVerifier      verifier_settlement;
    WithdrawalVerifier      verifier_withdrawal;
    BetCancelVerifier       verifier_bet_cancel;
    CancelCreditVerifier    verifier_cancel_credit;

    // ── IVerifier adapters (Vault-compatible interface) ───────────────────────
    BetAuthGroth16Adapter          adapter_bet_auth;
    SettlementCreditGroth16Adapter adapter_settlement;
    WithdrawalGroth16Adapter       adapter_withdrawal;
    BetCancelGroth16Adapter        adapter_bet_cancel;
    CancelCreditGroth16Adapter     adapter_cancel_credit;

    function setUp() public {
        verifier_bet_auth      = new BetAuthVerifier();
        verifier_settlement    = new SettlementVerifier();
        verifier_withdrawal    = new WithdrawalVerifier();
        verifier_bet_cancel    = new BetCancelVerifier();
        verifier_cancel_credit = new CancelCreditVerifier();

        adapter_bet_auth      = new BetAuthGroth16Adapter(address(verifier_bet_auth));
        adapter_settlement    = new SettlementCreditGroth16Adapter(address(verifier_settlement));
        adapter_withdrawal    = new WithdrawalGroth16Adapter(address(verifier_withdrawal));
        adapter_bet_cancel    = new BetCancelGroth16Adapter(address(verifier_bet_cancel));
        adapter_cancel_credit = new CancelCreditGroth16Adapter(address(verifier_cancel_credit));
    }

    // ── Public input builders ─────────────────────────────────────────────────

    function _betAuthInputs() internal pure returns (bytes32[] memory pi) {
        pi = new bytes32[](9);
        pi[0] = 0x20a3b0d4c0af766c64773096f2e9f15710ca0396dd73997de964df9919e2f8d3; // merkle_root
        pi[1] = 0x28bb28a2c7566e896a177dc7328d4298d197973bcac177fb8291984a1cc43b7f; // nullifier
        pi[2] = 0x1eda1feab9537758105917fe853bff050cd21c90efe0be0ec5f04b114af423a0; // new_commitment
        pi[3] = bytes32(uint256(100_000_000)); // bet_amount
        pi[4] = bytes32(uint256(65_000_000));  // price
        pi[5] = bytes32(uint256(153_846_153)); // expected_shares
        pi[6] = bytes32(uint256(1));           // market_id
        pi[7] = bytes32(uint256(1));           // outcome_side
        pi[8] = bytes32(uint256(2));           // position_id
    }

    function _settlementInputs() internal pure returns (bytes32[] memory pi) {
        pi = new bytes32[](8);
        pi[0] = 0x084bfcc0b5f14293388fdf7099cb75fbb76b55d15d8ea2693e05423f43af65f9; // merkle_root
        pi[1] = 0x07a76f71ef648dd62cdea92af5fe42fe84ef256a22d5f292b6381d1265fa7f89; // nullifier
        pi[2] = 0x2cad1d785e48e16d93bc48768910bc3fffaebb04008b6044d64ba540ff23689f; // new_commitment
        pi[3] = bytes32(uint256(42));          // nullifier_of_bet
        pi[4] = bytes32(uint256(1));           // market_id
        pi[5] = bytes32(uint256(500_000));     // payout_per_share
        pi[6] = bytes32(uint256(1_000));       // shares_held
        pi[7] = bytes32(uint256(500_000_000)); // total_credit
    }

    function _withdrawalInputs() internal pure returns (bytes32[] memory pi) {
        pi = new bytes32[](4);
        pi[0] = 0x1f9656507de3081de661e01a28c8f1ec84ea212f62b2d7ff16f81946744169e2; // merkle_root
        pi[1] = 0x2eaa00ff94aa542b726083d39a960fa6c3f79dded2d9bb24511ac009971ee7ed; // nullifier
        pi[2] = bytes32(uint256(500_000_000)); // withdrawal_amount
        pi[3] = 0x2b7f013908db29510be8293855a5e8b28afae599fea3d881345d81e99cb40de3; // recipient_hash
    }

    function _betCancelInputs() internal pure returns (bytes32[] memory pi) {
        pi = new bytes32[](5);
        pi[0] = 0x2c265359f57b9867ff9ce9be1a4c0c9f1b63d3ff9d886e63f9919b47d0f4f367; // merkle_root
        pi[1] = 0x007af346e2d304279e79e0a9f3023f771294a78acb70e73f90afe27cad401e81; // nullifier
        pi[2] = 0x055a760284f0ec59ccd2fc9e5a226ee0df970142480be0e004feb11d6e634718; // new_commitment
        pi[3] = bytes32(uint256(42));          // nullifier_of_bet
        pi[4] = bytes32(uint256(100_000_000)); // bet_amount
    }

    function _cancelCreditInputs() internal pure returns (bytes32[] memory pi) {
        pi = new bytes32[](6);
        pi[0] = 0x05d793a5e0980e6572815790369addbe845a3f0a0ee0554ffedf7cc6d7736f15; // merkle_root
        pi[1] = 0x115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a; // nullifier
        pi[2] = 0x183cae0d5276cddcd9de623ffbb10e8d2469df198b4b654882d82594117887ca; // new_commitment
        pi[3] = bytes32(uint256(43));          // nullifier_of_bet
        pi[4] = bytes32(uint256(99));          // market_id
        pi[5] = bytes32(uint256(100_000_000)); // bet_amount
    }

    // ── Via adapter (IVerifier interface — what Vault calls) ──────────────────

    function test_gasBench_Groth16_betAuth() public {
        bytes memory proof = vm.readFileBinary(string.concat(BENCH, "bet_auth.proof"));
        bool ok = adapter_bet_auth.verify(proof, _betAuthInputs());
        assertTrue(ok, "Groth16 bet_auth verify failed");
    }

    function test_gasBench_Groth16_settlement() public {
        bytes memory proof = vm.readFileBinary(string.concat(BENCH, "settlement_credit.proof"));
        bool ok = adapter_settlement.verify(proof, _settlementInputs());
        assertTrue(ok, "Groth16 settlement_credit verify failed");
    }

    function test_gasBench_Groth16_withdrawal() public {
        bytes memory proof = vm.readFileBinary(string.concat(BENCH, "withdrawal.proof"));
        bool ok = adapter_withdrawal.verify(proof, _withdrawalInputs());
        assertTrue(ok, "Groth16 withdrawal verify failed");
    }

    function test_gasBench_Groth16_betCancel() public {
        bytes memory proof = vm.readFileBinary(string.concat(BENCH, "bet_cancel.proof"));
        bool ok = adapter_bet_cancel.verify(proof, _betCancelInputs());
        assertTrue(ok, "Groth16 bet_cancel verify failed");
    }

    function test_gasBench_Groth16_cancelCredit() public {
        bytes memory proof = vm.readFileBinary(string.concat(BENCH, "cancel_credit.proof"));
        bool ok = adapter_cancel_credit.verify(proof, _cancelCreditInputs());
        assertTrue(ok, "Groth16 cancel_credit verify failed");
    }
}
